version: "3"

services:
  db:
    image: mysql/mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "mc"
      MYSQL_ROOT_PASSWORD: ""
    restart: always
    entrypoint: 
      sh -c "
            echo 'CREATE DATABASE IF NOT EXISTS mc;'
            "
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      PAPERBUILD: "387"
      VERSION: ${VERSION}
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./${VERSION}:/data
volumes:
  db:
    driver: local