version: '3'
services:
  db:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - '3306:3306'
    expose:
      - "3306"
    volumes:
      - "./database:/var/lib/mysql"
      - "./init:/docker-entrypoint-initdb.d"
  mc:
    image: itzg/minecraft-server
    ports:
      - '25565:25565'
    environment:
      EULA: 'TRUE'
      TYPE: PAPER
      PAPERBUILD: '388'
      MEMORY: 12G
      VERSION: '${VERSION}'
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - './${VERSION}:/data'