name: Script
version: 1.0
main: de.hiyamacity.main.Main
author: AhegaHOE
api-version: 1.16
commands:
  ping:
    description: Allows the player to check their ping.
  stats:
    description: Allows the player to see their stats.
  gm:
    description: Allows the player to change their game mode.
    aliases: [ gamemode ]
  pay:
    description: Allows the player to pay money to other players.
  info:
    description: Allows the player to get informations.
  me:
    description: Allows the player to do actions.
  kiss:
    description: Allows the player to kiss other players.
  time:
    description: Allows the player to get the current time.
  dice:
    description: Allows the player to roll a dice.
  m:
    description: Allows the player to message other players.
    aliases: [ message ]
  show-finances:
    description: Allows the player to show their finances to other players.
    aliases: [ showfinances ]
  deaths:
    description: Allows the player to see the deathcount.
  vanish:
    description: Allows the player to hide themselves and others.
  slap:
    description: Allows the player to slap themselves and others.
  house:
    description: Allows the player to handle some stuff in the house system.
  shop:
    description: Allows the player to interact with shops.
  tp:
    description: Allows the player to teleport them or others to specific locations.
    aliases: [ teleport ]
  heal:
    description: Allows the player to heal themselves.
  kick:
    description: Allows the player to kick other players.